CREATE TABLE trips(
id BIGSERIAL PRIMARY KEY,
user_id BIGINT NOT NULL,
city VARCHAR(100) NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL,
CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);